[package]
name = "pugbot"
version = "0.1.0"
authors = ["Matt DeBoard <mdeboard@truecar.com>"]
features = [ "const_fn" ]

[lib]
name = "pugbot"
path = "src/pugbot/lib.rs"

[[bin]]
name = "pugbot"
path = "src/main.rs"
test = false

[dependencies]
bigdecimal = "*"
diesel = { version = "*", features = ["chrono", "postgres", "serde_json", "huge-tables", "numeric", "uuid"] }
diesel_cli = { features = ["postgres"] }
diesel_codegen = { version = "*", features = ["postgres"] }
env_logger = "~0.4"
glicko2 = "*"
kankyo = "~0.1"
log = "~0.3"
num = "*"
r2d2 = "*"
r2d2-diesel = "*"
rand = "*"
serde = "^1.0"
serde_derive = "^1.0"
serde_json = "^1.0"
serenity = { git = "https://github.com/zeyla/serenity.git", features = ["cache", "framework", "standard_framework"] }
typemap = "0.3"
