jobs:
  build:
    docker:
      - image: cimg/rust:1.52.1
    steps:
      - checkout
      - run: cargo --version
      - run: cp rename-this-to-.env .env
      - run: cargo test --lib
      - run: cargo test --lib -- --test-threads=1 --ignored models::game_config
